FROM centos

RUN echo 'Centos update'; \
  yum update -y && \
  yum upgrade -y

RUN echo 'Docker install'; \
  yum install yum-utils -y && \
  yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo -y && \
  yum install docker-ce docker-ce-cli containerd.io -y
